
include(ExternalProject)
# External project : OGRE_DEPENDENCIES (needed for OGRE)
ExternalProject_Add(ogredeps
HG_REPOSITORY https://bitbucket.org/cabalistic/ogredeps
CMAKE_ARGS -DCMAKE_INSTALL_PREFIX:PATH=${CMAKE_INSTALL_PREFIX};
-DCMAKE_BUILD_TYPE:STRING=${BUILD_TARGET};
-DBUILD_SHARED_LIBS:BOOL=TRUE
PREFIX ${DEP_DIR}/ogreDeps)

# External project : OGRE (render engine)
ExternalProject_Add(OGRE
HG_REPOSITORY http://bitbucket.org/sinbad/ogre/
HG_TAG ${OGRE_SDK_VERSION}
CMAKE_ARGS -DCMAKE_INSTALL_PREFIX:PATH=${CMAKE_INSTALL_PREFIX};
-DCMAKE_BUILD_TYPE:STRING=${BUILD_TARGET};
-DBUILD_SHARED_LIBS:BOOL=TRUE
PREFIX ${DEP_DIR}/OGRE_SDK
DEPENDS ogredeps)

# External project : OPENAL (audio library)
ExternalProject_Add(openAL
GIT_REPOSITORY git://repo.or.cz/openal-soft.git
GIT_TAG ${OPENAL_VERSION_TAG}
PREFIX ${DEP_DIR}/openAL
CMAKE_ARGS -DCMAKE_INSTALL_PREFIX:PATH=${CMAKE_INSTALL_PREFIX};
-DCMAKE_BUILD_TYPE:STRING=${BUILD_TARGET};
-DBUILD_SHARED_LIBS:BOOL=TRUE)

## External project : BULLET PHYSICS (physics engine)
ExternalProject_Add(BULLET
SVN_REPOSITORY http://bullet.googlecode.com/svn/trunk/
CMAKE_ARGS -DCMAKE_INSTALL_PREFIX:PATH=${CMAKE_INSTALL_PREFIX};
-DCMAKE_BUILD_TYPE:STRING=${BUILD_TARGET};
-DBUILD_SHARED_LIBS:BOOL=TRUE;
-DINSTALL_EXTRA_LIBS:BOOL=TRUE;
-DUSE_CUSTOM_VECTOR_MATH:BOOL=TRUE
PREFIX ${DEP_DIR}/BULLET)

## External project : OGRE BULLET PLUGIN 
ExternalProject_Add(Ogre_Bullet
GIT_REPOSITORY https://bitbucket.org/alexeyknyshev/ogrebullet.git
PREFIX ${DEP_DIR}/Ogre_Bullet
CMAKE_ARGS -DCMAKE_INSTALL_PREFIX:PATH=${CMAKE_INSTALL_PREFIX};
-DCMAKE_BUILD_TYPE:STRING=${BUILD_TARGET};
-DBUILD_SHARED_LIBS:BOOL=TRUE;
-DBULLET_INCLUDE_DIR:PATH=${CMAKE_INSTALL_PREFIX}/include/bullet;
-DBULLET_INCLUDE_COLLISION_DIR:PATH=${CMAKE_INSTALL_PREFIX}/include/bullet/BulletCollision;
-DBULLET_INCLUDE_DYNAMICS_DIR:PATH=${CMAKE_INSTALL_PREFIX}/include/bullet/BulletDynamics;
-DBULLET_INCLUDE_CONVEXDECOMPOSITION_DIR:PATH=${CMAKE_INSTALL_PREFIX}/include/bullet/ConvexDecomposition;
-DBULLET_INCLUDE_SOFTBODY_DIR:PATH=${CMAKE_INSTALL_PREFIX}/include/bullet/BulletSoftBody;
-DBULLET_INCLUDE_LINEARMATH_DIR:PATH=${CMAKE_INSTALL_PREFIX}/include/bullet/LinearMath
DEPENDS OGRE BULLET)

# new version of CEGUI needs the new version of GLM
# External project : OpenGL Math Library
#ExternalProject_Add(
#    glm
#    PREFIX ${CMAKE_BINARY_DIR}/glm
#    GIT_REPOSITORY https://github.com/g-truc/glm.git
#    CONFIGURE_COMMAND ""
#    BUILD_COMMAND ""
#    INSTALL_COMMAND ${CMAKE_COMMAND} -E copy_directory
#                    <SOURCE_DIR>/glm ${CMAKE_BINARY_DIR}/installed/glm
#    LOG_DOWNLOAD ON
#    LOG_INSTALL ON
#    )
    
#https://bitbucket.org/cegui/cegui
#https://danduk82_@bitbucket.org/danduk82_/cegui
#HG_TAG ${CEGUI_SDK_VERSION}
#-DGLM_H_PATH:PATH=${GLM_H_PATH}

# External project : CEGUI (GUI-system)
ExternalProject_Add(CEGUI
HG_REPOSITORY https://bitbucket.org/cegui/cegui
HG_TAG ${CEGUI_SDK_VERSION}
CMAKE_ARGS -DCMAKE_INSTALL_PREFIX:PATH=${CMAKE_INSTALL_PREFIX};
-DCMAKE_BUILD_TYPE:STRING=${BUILD_TARGET};
-DBUILD_SHARED_LIBS:BOOL=TRUE;
-DCEGUI_BUILD_PYTHON_MODULES:BOOL=OFF;
-DCEGUI_BUILD_RENDERER_OGRE:BOOL=ON;
-DOIS_LIB_DBG:PATH=${LIBOISD};
-DOGRE_LIB_DBG:PATH=${LIBOGRED};
-DOIS_LIB:PATH=${LIBOIS};
-DOGRE_LIB:PATH=${LIBOGRE};
-DOGRE_H_PATH:PATH=${OGRE_HOME}/include/OGRE;
-DOIS_H_PATH:PATH=${OGRE_HOME}/include/OIS;
-DCEGUI_SAMPLES_ENABLED:BOOL=FALSE;
PREFIX ${DEP_DIR}/CEGUI
DEPENDS OGRE)

# official site: https://github.com/imperative/CommunityHydrax
# personal fork: https://github.com/danduk82/CommunityHydrax.git
# External project : OGRE HYDRAX PLUGIN (OGRE plugin for sea)
ExternalProject_Add(HYDRAX
GIT_REPOSITORY https://github.com/danduk82/CommunityHydrax.git
PREFIX ${DEP_DIR}/Ogre_hydrax
CMAKE_ARGS -DCMAKE_INSTALL_PREFIX:PATH=${CMAKE_INSTALL_PREFIX};
-DCMAKE_BUILD_TYPE:STRING=${BUILD_TARGET};
-DCMAKE_MODULE_PATH:PATH=${CMAKE_INSTALL_PREFIX}/lib/OGRE/cmake;
-DBUILD_SHARED_LIBS:BOOL=TRUE;
DEPENDS OGRE)

# External project : OGRE CAMERA CONTROL SYSTEM PLUGIN (plugin for easy camera handling)
ExternalProject_Add(CCS
SVN_REPOSITORY svn://svn.code.sf.net/p/ogre-ccs/code/trunk
PREFIX ${DEP_DIR}/Ogre_CCS
CMAKE_ARGS -DCMAKE_INSTALL_PREFIX:PATH=${CMAKE_INSTALL_PREFIX};
-DCMAKE_BUILD_TYPE:STRING=${BUILD_TARGET};
-DBUILD_SHARED_LIBS:BOOL=TRUE;
DEPENDS OGRE)

# "original" GIT_REPOSITORY https://github.com/th3flyboy/SkyX.git
# using my own fork to be sure it exists
# External project : OGRE SKYX PLUGIN
ExternalProject_Add(SKYX
GIT_REPOSITORY https://github.com/danduk82/SkyX.git
PREFIX ${DEP_DIR}/Ogre_SkyX
CMAKE_ARGS -DCMAKE_INSTALL_PREFIX:PATH=${CMAKE_INSTALL_PREFIX};
-DCMAKE_BUILD_TYPE:STRING=${BUILD_TARGET};
-DOGRE_HOME:PATH=${OGRE_HOME};
-DSKYX_DEPENDENCIES_DIR:PATH=${OGRE_HOME};
-DSKYX_BUILD_SAMPLES:BOOL=FALSE;
-DSKYX_INSTALL_SAMPLES:BOOL=FALSE;
-DCMAKE_MODULE_PATH:PATH=${CMAKE_INSTALL_PREFIX}/lib/OGRE/cmake;
-DBUILD_SHARED_LIBS:BOOL=TRUE;
DEPENDS OGRE)

